# Generated by Django 5.1.2 on 2024-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("date_published", models.DateField(auto_now_add=True)),
                ("content", models.TextField()),
                ("url", models.URLField(unique=True)),
            ],
        ),
    ]
