# Generated by Django 5.1.2 on 2024-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
