# Generated by Django 5.1.2 on 2024-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles1", "0002_alter_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_published",
            field=models.DateField(),
        ),
    ]
