# Generated by Django 5.1.2 on 2024-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles1", "0003_alter_article_date_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_published",
            field=models.DateField(auto_now_add=True),
        ),
    ]
